Repository seanlesch/CilantroAudit, pull requests merged in 2019-10, with the labels that each got.

#36 Ticket-16: Create And Store Audit Template
  integration_tests.sh
  source/audit_template.py
  source/main.py
  tests/component/comptest.py
  tests/integration/test_audit_template.py
  tests/unit/test_audit_template.py
  tests/unit/test_audit_template_builder.py
  tests/unit/test_question.py
  tests/unit/test_severity.py
  tests/unit/unittest.py
  unit_tests.sh
Labels: backend

#39 Ticket-12: Create and Store Completed Audit
  README.md
  source/audit_template.py
  source/completed_audit.py
  source/main.py
  tests/integration/test_audit_template.py
  tests/integration/test_completed_audit.py
  tests/unit/test_answer.py
  tests/unit/test_audit_template.py
  tests/unit/test_completed_audit.py
  tests/unit/test_completed_audit_builder.py
  tests/unit/test_question.py
  tests/unit/test_response.py
Labels: backend

#43 Added Documentation for setup.py Installation
  README.md
Labels: documentation

#48 Merging frontend code into master.
  cilantro_audit/auditor_page.py
  cilantro_audit/create_audit_page.py
  cilantro_audit/home_page.py
  cilantro_audit/question_module.py
  cilantro_audit/view_audits_page.py
  cilantro_audit/widgets/admin_page.kv
  cilantro_audit/widgets/auditor_page.kv
  cilantro_audit/widgets/create_audit_page.kv
  cilantro_audit/widgets/home_page.kv
  cilantro_audit/widgets/question_module.kv
Labels: frontend
